name: 'Incremental Version plugin/theme'
description: "Action permettant d'incrémenter la version d'un plugin ou un thème"
inputs:
  folder:  # id of input
    description: 'Folder plugin or theme'
    required: true
    default: ''
  indexFile:  # id of input
    description: 'Enter file plugin or theme'
    required: false
    default: ''
outputs:
  json: # id of output
    description: 'Json informations comment WP'
  contentUpdated: # id of output
    description: 'Content updated style.css or indexFile plugin.'
runs:
  using: 'node16'
  main: 'versionning-wp.js'