name: Code style validation
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          # select the adequate registry whether you want to publish to Github Packages or NPM
          #registry-url: 'https://registry.npmjs.org'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install packages
        run: npm ci
      - name: Validate JS code style
        run: npx eslint src/** --ignore-pattern "src/editor\.scss"
      - name: Validate CSS code style
        run: npx stylelint "src/**/*.scss"
