<?php 
function createCustomFields() {
  acf_add_local_field_group(array(
      'key' => 'group_60b8cfa3748c6',
      'title' => 'Informations de contact',
      'fields' => array(
          array(
              'key' => 'field_60c35a1dbb564',
              'label' => 'Page à afficher sur la carte ?',
              'name' => 'on_map',
              'type' => 'true_false',
              'instructions' => 'Cochez cette case si vous souhaitez que cette page soit liée à la carte géolocalisée',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
              ),
              'show_in_rest' => 1,
              'edit_in_rest' => 0,
              'message' => '',
              'default_value' => 0,
              'ui' => 0,
              'ui_on_text' => '',
              'ui_off_text' => '',
          ),
          array(
              'key' => 'field_60bf14ee836e6',
              'label' => "Ordre d'apparition",
              'name' => 'order',
              'type' => 'number',
              'instructions' => "Saisissez ici un nombre indiquant la position de la filiale dans la remontée. 1 correspond au premier élément de la liste, 10 au 10e. Entrez 0 pour forcer l'élément à apparaître en dernier.",
              'required' => 0,
              'conditional_logic' => array(
                  array(
                      array(
                          'field' => 'field_60c35a1dbb564',
                          'operator' => '==',
                          'value' => '1',
                      ),
                  ),
              ),
              'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
              ),
              'show_in_rest' => 1,
              'edit_in_rest' => 0,
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_60bf14ee836c5',
              'label' => 'Nom de la filiale',
              'name' => 'nom',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                  array(
                      array(
                          'field' => 'field_60c35a1dbb564',
                          'operator' => '==',
                          'value' => '1',
                      ),
                  ),
              ),
              'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
              ),
              'show_in_rest' => 1,
              'edit_in_rest' => 0,
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_60b8df4238111',
              'label' => 'Adresse',
              'name' => 'adresse1',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                  array(
                      array(
                          'field' => 'field_60c35a1dbb564',
                          'operator' => '==',
                          'value' => '1',
                      ),
                  ),
              ),
              'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
              ),
              'show_in_rest' => 1,
              'edit_in_rest' => 0,
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_60bf149a836c2',
              'label' => 'Complément d\'adresse',
              'name' => 'adresse2',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                  array(
                      array(
                          'field' => 'field_60c35a1dbb564',
                          'operator' => '==',
                          'value' => '1',
                      ),
                  ),
              ),
              'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
              ),
              'show_in_rest' => 1,
              'edit_in_rest' => 0,
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_60bf14b1836c3',
              'label' => 'Code postal',
              'name' => 'code_postal',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                  array(
                      array(
                          'field' => 'field_60c35a1dbb564',
                          'operator' => '==',
                          'value' => '1',
                      ),
                  ),
              ),
              'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
              ),
              'show_in_rest' => 1,
              'edit_in_rest' => 0,
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_60bf14d4836c4',
              'label' => 'Ville',
              'name' => 'ville',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                  array(
                      array(
                          'field' => 'field_60c35a1dbb564',
                          'operator' => '==',
                          'value' => '1',
                      ),
                  ),
              ),
              'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
              ),
              'show_in_rest' => 1,
              'edit_in_rest' => 0,
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_60b8e00dcb6ce',
              'label' => 'E-mail',
              'name' => 'email',
              'type' => 'email',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                  array(
                      array(
                          'field' => 'field_60c35a1dbb564',
                          'operator' => '==',
                          'value' => '1',
                      ),
                  ),
              ),
              'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
              ),
              'show_in_rest' => 1,
              'edit_in_rest' => 0,
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
          ),
          array(
              'key' => 'field_60b8e021cb6cf',
              'label' => 'Téléphone',
              'name' => 'telephone',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                  array(
                      array(
                          'field' => 'field_60c35a1dbb564',
                          'operator' => '==',
                          'value' => '1',
                      ),
                  ),
              ),
              'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
              ),
              'show_in_rest' => 1,
              'edit_in_rest' => 0,
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
          ),
          array(
              'key' => 'field_60b8e021cb6d0',
              'label' => 'Téléphone #2',
              'name' => 'telephone2',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                  array(
                      array(
                          'field' => 'field_60c35a1dbb564',
                          'operator' => '==',
                          'value' => '1',
                      ),
                  ),
              ),
              'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
              ),
              'show_in_rest' => 1,
              'edit_in_rest' => 0,
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
          ),
          array(
            'key' => 'field_612e28d71b9a2',
            'label' => 'Logo',
            'name' => 'logo',
            'type' => 'image',
            'instructions' => 'Ajouter le logo de la filiale',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_60c35a1dbb564',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => 'filiale_logo',
              'id' => '',
            ),
            'show_in_rest' => 1,
            'edit_in_rest' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '.png, .jpeg, .jpg',
          ),
      ),
      'location' => array(
          array(
              array(
                  'param' => 'post_type',
                  'operator' => '==',
                  'value' => 'page',
              ),
          ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
  ));
}

?>
